services:
  - type: web
    name: ultrascrap
    runtime: python
    rootDir: ultrascrap
    buildCommand: bash build.sh
    startCommand: python backend/main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/.playwright
    region: oregon